/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'Banner-Form': RouteRecordInfo<'Banner-Form', 'banner-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Banner-List': RouteRecordInfo<'Banner-List', '/Banner/List', Record<never, never>, Record<never, never>>,
    'Company-Form': RouteRecordInfo<'Company-Form', 'company-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Company-List': RouteRecordInfo<'Company-List', '/Company/List', Record<never, never>, Record<never, never>>,
    'DashboardStudent': RouteRecordInfo<'DashboardStudent', '/dashboard/student', Record<never, never>, Record<never, never>>,
    'DashboardTeacher': RouteRecordInfo<'DashboardTeacher', '/dashboard/teacher', Record<never, never>, Record<never, never>>,
    'Grade-Form': RouteRecordInfo<'Grade-Form', 'grade-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Grade-List': RouteRecordInfo<'Grade-List', '/Grade/List', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Note-Index': RouteRecordInfo<'Note-Index', '/Note/Index', Record<never, never>, Record<never, never>>,
    'Pw-home': RouteRecordInfo<'Pw-home', '/', Record<never, never>, Record<never, never>>,
    'Pw-GradeSectionNotes': RouteRecordInfo<'Pw-GradeSectionNotes', '/gradeSectionNotes/:school_id/:grade_id/:section_id', Record<never, never>, Record<never, never>>,
    'Pw-GradeSectionTeachers': RouteRecordInfo<'Pw-GradeSectionTeachers', '/gradeSectionTeachers/:school_id/:grade_id/:section_id', Record<never, never>, Record<never, never>>,
    'Pw-school': RouteRecordInfo<'Pw-school', '/school/:school_id', Record<never, never>, Record<never, never>>,
    'Pw-ServiceData': RouteRecordInfo<'Pw-ServiceData', '/school/:school_id/service/:service_id', Record<never, never>, Record<never, never>>,
    'Pw-SubjectPennding': RouteRecordInfo<'Pw-SubjectPennding', '/school/:school_id/subjectPennding', Record<never, never>, Record<never, never>>,
    'pw-contact-area': RouteRecordInfo<'pw-contact-area', '/Pw/ContactArea', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'Service-List': RouteRecordInfo<'Service-List', '/Service/List', Record<never, never>, Record<never, never>>,
    'Service-Form': RouteRecordInfo<'Service-Form', 'service-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Student-Form': RouteRecordInfo<'Student-Form', '/student-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Student-Index': RouteRecordInfo<'Student-Index', '/Student/Index', Record<never, never>, Record<never, never>>,
    'Subject-List': RouteRecordInfo<'Subject-List', '/Subject/List', Record<never, never>, Record<never, never>>,
    'Subject-Form': RouteRecordInfo<'Subject-Form', 'subject-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'Teacher-Order': RouteRecordInfo<'Teacher-Order', '/teacher-Order', Record<never, never>, Record<never, never>>,
    'Teacher-Planning': RouteRecordInfo<'Teacher-Planning', '/teacher-Planning/:id?', Record<never, never>, Record<never, never>>,
    'Teacher-List': RouteRecordInfo<'Teacher-List', '/Teacher/List', Record<never, never>, Record<never, never>>,
    'Teacher-Form': RouteRecordInfo<'Teacher-Form', 'teacher-form/:action/:id?', Record<never, never>, Record<never, never>>,
    'user-access-role-components-modal-form': RouteRecordInfo<'user-access-role-components-modal-form', '/UserAccess/Role/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'Role-List': RouteRecordInfo<'Role-List', '/UserAccess/Role/List', Record<never, never>, Record<never, never>>,
    'user-access-users-components-modal-form': RouteRecordInfo<'user-access-users-components-modal-form', '/UserAccess/Users/Components/ModalForm', Record<never, never>, Record<never, never>>,
    'User-List': RouteRecordInfo<'User-List', '/UserAccess/Users/List', Record<never, never>, Record<never, never>>,
  }
}
